### ISSUE TITLE
ModuleNotFoundError: No module named 'LinkGPT'

### ISSUE THREAD

**Issue by William3242** [twelfth-star/LinkGPT#2]
When I try to run the command `bash amazon_clothing_20k/train_linkgpt.sh`,  there is a error reported: 
(https://github.com/user-attachments/assets/50520431-7c21-4419-9619-c817bda4a7af) I want to find the solution the this error.
```
(linkgpt) wlhuang@ybcs:~/llm/LinkGPT/scripts$ bash amazon_clothing_20k/train_linkgpt.sh
/home/wlhuang/llm/LinkGPT:
Project Path: /home/wlhuang/llm/LinkGPT
Data Path: /home/wlhuang/llm/LinkGPT/data
WANDB_KEY: d7f4fdb74ad61dff6f2dc5a6522b521c0a28e4ac
/home/wlhuang/anaconda3/envs/linkgpt/lib/python3.9/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
{'model_name_or_path': 'meta-llama/Llama-2-7b-hf', 'text_embedding_method': 'cgtp', 'text_embedding_folder_path': '/home/wlhuang/llm/LinkGPT/data/datasets/amazon_clothing_20k', 'max_hop': 0, 'dataset_for_lm_path': '/home/wlhuang/llm/LinkGPT/data/datasets/amazon_clothing_20k/dataset_for_lm.pkl', 'ppr_data_path': '/home/wlhuang/llm/LinkGPT/data/datasets/amazon_clothing_20k/ppr_data.pt', 'output_dir': '/home/wlhuang/llm/LinkGPT/data/models/amazon_clothing_20k/linkgpt-llama2-7b-cgtp', 'dataset_name': 'amazon_clothing_20k', 'lp_dataset_path': '/home/wlhuang/llm/LinkGPT/data/datasets/amazon_clothing_20k/ft_yn_dataset.pkl', 'lp_ablate_pairwise_encoding': False, 'lp_ablate_node_encoding': False, 'lp_learn_text': False, 'lp_learn_all': False, 'np_dataset_path': '/home/wlhuang/llm/LinkGPT/data/datasets/amazon_clothing_20k/ft_np_dataset.pkl', 'np_ablate_node_encoding': False, 'np_learn_src_text': False, 'np_learn_all': False, 'device_setting': 'cuda:0', 'wandb_key': 'd7f4fdb74ad61dff6f2dc5a6522b521c0a28e4ac', 'project_name': 'amazon_clothing_20k_ft', 'run_name': 'linkgpt-llama2-7b-cgtp', 'finetuning_type': 'lora', 'per_device_train_batch_size': 8, 'gradient_accumulation_steps': 4, 'lr_scheduler_type': 'cosine', 'logging_steps': 1, 'save_steps': 10000, 'learning_rate': 0.0003, 'weight_decay': 0, 'warmup_ratio': 0, 'max_grad_norm': 1, 'num_train_epochs_stage1': 1, 'num_train_epochs_stage2': 1, 'fp16': True, 'report_to': 'wandb', 'dataloader_num_workers': 4, 'dataloader_prefetch_factor': 8, 'lora_target': 'q_proj,v_proj', 'lora_alpha': 32.0, 'lora_rank': 16, 'lora_dropout': 0.0, 'freeze_graph_related_modules_in_stage2': True, 'stage1_task': 'np,lp', 'stage2_task': 'np,lp', 'node_proj_num_layers': 2}
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/wlhuang/.netrc
text_emb_path : /home/wlhuang/llm/LinkGPT/data/datasets/amazon_clothing_20k/text_emb_cgtp.pt
Traceback (most recent call last):
  File "/home/wlhuang/llm/LinkGPT/linkgpt/train/train.py", line 285, in <module>
    main()
  File "/home/wlhuang/llm/LinkGPT/linkgpt/train/train.py", line 146, in main
    lp_dataset = basics.load_pickle(args.lp_dataset_path)
  File "/home/wlhuang/llm/LinkGPT/linkgpt/utils/basics.py", line 69, in load_pickle
    data = pickle.load(f)
ModuleNotFoundError: No module named 'LinkGPT'
Traceback (most recent call last):
  File "/home/wlhuang/llm/LinkGPT/linkgpt/train/train.py", line 285, in <module>
    main()
  File "/home/wlhuang/llm/LinkGPT/linkgpt/train/train.py", line 146, in main
    lp_dataset = basics.load_pickle(args.lp_dataset_path)
  File "/home/wlhuang/llm/LinkGPT/linkgpt/utils/basics.py", line 69, in load_pickle
    data = pickle.load(f)
ModuleNotFoundError: No module named 'LinkGPT'
```

**Comment by twelfth-star** [comment]
Thank you for your issue. This bug is due to the fact that I updated the structure of the code but forgot to to update the dataset file I shared via Google Drive accordingly. I have updated it and you need to download the latest version of our dataset from here: https://drive.google.com/file/d/1-_57MT-Mtp_oYnqSc0Kos7BpDBAyPuy5/view?usp=drive_link
